name: 'Chat GPT Code Peer Review'
description: 'This action performs a code peer review using OpenAI ChatGPT API and functions.'
inputs:
  openai_api_key:
    description: 'The API key for accessing the OpenAI ChatGPT API.'
    required: true
  target_branch:
    description: 'The target branch for the git diff to run against.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
